name: Backend CI

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"
  workflow_dispatch: {}

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: go build -v .

      - name: Run Test
        run: |
          go test -v ./...
